Fix the integer failback value, the code expects a string
When I run the discover-service without domain I have

bash-5.1$ ../bin/discover-ldap 
Traceback (most recent call last):
  File "/home/ejabberd3/.config/state/../bin/discover-services", line 40, in <module>
    print('DOVECOT_LDAP_PORT=' + odom['port'], file=denv)
TypeError: can only concatenate str (not "int") to str